<?php

namespace app\modules\admin\components;

use nullref\admin\components\MenuBuilder;
use nullref\admin\interfaces\IMenuBuilder;

class MenuBilder extends MenuBuilder implements IMenuBuilder
{
    public function filterByRole($menu, $role, $paramName = 'roles')
    {
        return parent::filterByRole($menu, $role, $paramName); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $items
     * @return array
     */
    public function build($items)
    {

        foreach ($items as $key => $elements) {
            if (!empty($elements)) {
                $new_items[$key] = $elements;
            }

        }
        return $new_items;
    }
}